language: node_js

node_js:
  - "node"

branches:
  only:
    - master

cache:
  bundler: true
  directories:
    - node_modules
    - $HOME/.nvm
    - $HOME/.npm

before_install:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

before_script:
  - npm prune

script:
  - yarn run lint
  - yarn run flow
  - yarn test

after_success:
  - yarn run semantic-release

notifications:
  email: false
