language: node_js

node_js:
  - "node"

branches:
  only:
    - master

cache:
  directories:
    - node_modules
    - $HOME/.nvm
    - $HOME/.npm

before_install:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

script:
  - yarn run check

after_success:
  - yarn run semantic-release

notifications:
  email: false
