language: node_js

node_js:
  - "node"

branches:
  only:
    - master

cache:
  directories:
    - node_modules
    - $HOME/.nvm
    - $HOME/.npm

before_install:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

script:
  - if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then yarn run check; fi
  - if [ "$TRAVIS_EVENT_TYPE" == "push" ] && [ "$TRAVIS_BRANCH" = "master" ]; then yarn run semantic-release; fi

after_success:
  - yarn run semantic-release

notifications:
  email:
    recipients:
      - wongterrencew@gmail.com
    on_success: never
    on_failure: always
