// flow-typed signature: cf1c93cdf2d052923281785ee6fe0ea2
// flow-typed version: <<STUB>>/mocha-mock_v^1.2.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mocha-mock/lib/index' {
  declare module.exports: any;
}

declare module 'mocha-mock/lib/mocha-mock' {
  declare module.exports: any;
}

declare module 'mocha-mock/lib/mocha-mock.spec' {
  declare module.exports: any;
}

declare module 'mocha-mock/lib/mock-object/index' {
  declare module.exports: any;
}

declare module 'mocha-mock/lib/mock-object/mock-object' {
  declare module.exports: any;
}

declare module 'mocha-mock/lib/mock-object/mock-object.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mocha-mock/lib/index.js' {
  declare module.exports: $Exports<'mocha-mock/lib/index'>;
}
declare module 'mocha-mock/lib/mocha-mock.js' {
  declare module.exports: $Exports<'mocha-mock/lib/mocha-mock'>;
}
declare module 'mocha-mock/lib/mocha-mock.spec.js' {
  declare module.exports: $Exports<'mocha-mock/lib/mocha-mock.spec'>;
}
declare module 'mocha-mock/lib/mock-object/index.js' {
  declare module.exports: $Exports<'mocha-mock/lib/mock-object/index'>;
}
declare module 'mocha-mock/lib/mock-object/mock-object.js' {
  declare module.exports: $Exports<'mocha-mock/lib/mock-object/mock-object'>;
}
declare module 'mocha-mock/lib/mock-object/mock-object.spec.js' {
  declare module.exports: $Exports<'mocha-mock/lib/mock-object/mock-object.spec'>;
}
