// flow-typed signature: 1899c39af0f78bf74057dd7f91de37bb
// flow-typed version: <<STUB>>/pouchdb-adapter-memory_v^6.1.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pouchdb-adapter-memory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pouchdb-adapter-memory' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pouchdb-adapter-memory/lib/index.es' {
  declare module.exports: any;
}

declare module 'pouchdb-adapter-memory/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pouchdb-adapter-memory/lib/index.es.js' {
  declare module.exports: $Exports<'pouchdb-adapter-memory/lib/index.es'>;
}
declare module 'pouchdb-adapter-memory/lib/index.js' {
  declare module.exports: $Exports<'pouchdb-adapter-memory/lib/index'>;
}
