// flow-typed signature: 421a48f5204f12e3b24a952f645ac604
// flow-typed version: <<STUB>>/pouchdb_v^6.1.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pouchdb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pouchdb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pouchdb/dist/pouchdb-next' {
  declare module.exports: any;
}

declare module 'pouchdb/dist/pouchdb.fruitdown' {
  declare module.exports: any;
}

declare module 'pouchdb/dist/pouchdb.fruitdown.min' {
  declare module.exports: any;
}

declare module 'pouchdb/dist/pouchdb' {
  declare module.exports: any;
}

declare module 'pouchdb/dist/pouchdb.localstorage' {
  declare module.exports: any;
}

declare module 'pouchdb/dist/pouchdb.localstorage.min' {
  declare module.exports: any;
}

declare module 'pouchdb/dist/pouchdb.memory' {
  declare module.exports: any;
}

declare module 'pouchdb/dist/pouchdb.memory.min' {
  declare module.exports: any;
}

declare module 'pouchdb/dist/pouchdb.min' {
  declare module.exports: any;
}

declare module 'pouchdb/lib/index-browser.es' {
  declare module.exports: any;
}

declare module 'pouchdb/lib/index-browser' {
  declare module.exports: any;
}

declare module 'pouchdb/lib/index.es' {
  declare module.exports: any;
}

declare module 'pouchdb/lib/index' {
  declare module.exports: any;
}

declare module 'pouchdb/tonic-example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pouchdb/dist/pouchdb-next.js' {
  declare module.exports: $Exports<'pouchdb/dist/pouchdb-next'>;
}
declare module 'pouchdb/dist/pouchdb.fruitdown.js' {
  declare module.exports: $Exports<'pouchdb/dist/pouchdb.fruitdown'>;
}
declare module 'pouchdb/dist/pouchdb.fruitdown.min.js' {
  declare module.exports: $Exports<'pouchdb/dist/pouchdb.fruitdown.min'>;
}
declare module 'pouchdb/dist/pouchdb.js' {
  declare module.exports: $Exports<'pouchdb/dist/pouchdb'>;
}
declare module 'pouchdb/dist/pouchdb.localstorage.js' {
  declare module.exports: $Exports<'pouchdb/dist/pouchdb.localstorage'>;
}
declare module 'pouchdb/dist/pouchdb.localstorage.min.js' {
  declare module.exports: $Exports<'pouchdb/dist/pouchdb.localstorage.min'>;
}
declare module 'pouchdb/dist/pouchdb.memory.js' {
  declare module.exports: $Exports<'pouchdb/dist/pouchdb.memory'>;
}
declare module 'pouchdb/dist/pouchdb.memory.min.js' {
  declare module.exports: $Exports<'pouchdb/dist/pouchdb.memory.min'>;
}
declare module 'pouchdb/dist/pouchdb.min.js' {
  declare module.exports: $Exports<'pouchdb/dist/pouchdb.min'>;
}
declare module 'pouchdb/lib/index-browser.es.js' {
  declare module.exports: $Exports<'pouchdb/lib/index-browser.es'>;
}
declare module 'pouchdb/lib/index-browser.js' {
  declare module.exports: $Exports<'pouchdb/lib/index-browser'>;
}
declare module 'pouchdb/lib/index.es.js' {
  declare module.exports: $Exports<'pouchdb/lib/index.es'>;
}
declare module 'pouchdb/lib/index.js' {
  declare module.exports: $Exports<'pouchdb/lib/index'>;
}
declare module 'pouchdb/tonic-example.js' {
  declare module.exports: $Exports<'pouchdb/tonic-example'>;
}
