// flow-typed signature: c54fe972933b2a7b0302ca4d7e9d86fc
// flow-typed version: <<STUB>>/pouchdb-upsert_v^2.1.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pouchdb-upsert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pouchdb-upsert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pouchdb-upsert/dist/pouchdb.upsert' {
  declare module.exports: any;
}

declare module 'pouchdb-upsert/dist/pouchdb.upsert.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pouchdb-upsert/dist/pouchdb.upsert.js' {
  declare module.exports: $Exports<'pouchdb-upsert/dist/pouchdb.upsert'>;
}
declare module 'pouchdb-upsert/dist/pouchdb.upsert.min.js' {
  declare module.exports: $Exports<'pouchdb-upsert/dist/pouchdb.upsert.min'>;
}
declare module 'pouchdb-upsert/index' {
  declare module.exports: $Exports<'pouchdb-upsert'>;
}
declare module 'pouchdb-upsert/index.js' {
  declare module.exports: $Exports<'pouchdb-upsert'>;
}
