// flow-typed signature: 5d2874ace3ac71cc165ce2c94dceeb05
// flow-typed version: <<STUB>>/q-level_v^1.1.3/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'q-level'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'q-level' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'q-level/examples/callbacks' {
  declare module.exports: any;
}

declare module 'q-level/examples/promises' {
  declare module.exports: any;
}

declare module 'q-level/fromstream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'q-level/examples/callbacks.js' {
  declare module.exports: $Exports<'q-level/examples/callbacks'>;
}
declare module 'q-level/examples/promises.js' {
  declare module.exports: $Exports<'q-level/examples/promises'>;
}
declare module 'q-level/fromstream.js' {
  declare module.exports: $Exports<'q-level/fromstream'>;
}
declare module 'q-level/index' {
  declare module.exports: $Exports<'q-level'>;
}
declare module 'q-level/index.js' {
  declare module.exports: $Exports<'q-level'>;
}
