// flow-typed signature: 1f7039608fedb7f25d2c5ea262a95bc4
// flow-typed version: <<STUB>>/readline-sync_v^1.4.6/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'readline-sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'readline-sync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'readline-sync/lib/encrypt' {
  declare module.exports: any;
}

declare module 'readline-sync/lib/read.cs' {
  declare module.exports: any;
}

declare module 'readline-sync/lib/readline-sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'readline-sync/lib/encrypt.js' {
  declare module.exports: $Exports<'readline-sync/lib/encrypt'>;
}
declare module 'readline-sync/lib/read.cs.js' {
  declare module.exports: $Exports<'readline-sync/lib/read.cs'>;
}
declare module 'readline-sync/lib/readline-sync.js' {
  declare module.exports: $Exports<'readline-sync/lib/readline-sync'>;
}
